import clientPromise from '../config/mongoDB';
import { useSession } from 'next-auth/react';
import Image from 'next/image';
import React from 'react'
import style from '.././styles/AllPosts.module.css'
import Header from '../components/Header';
import Feed from '../components/Feed';
import CommentPost from '../components/commentPost';
import Head from 'next/head';
import { RxCross2 } from 'react-icons/Rx';
import { BsThreeDots } from 'react-icons/Bs';

export default function Alldata({ mflix }) {

    const { data: session } = useSession();

    const handleDelete = async (postId) => {
        try {
            let res = await fetch('http://localhost:3000/api/deletePost?id=' + postId, {
                method: "POST",
                headers: {
                    'Accept': 'application/json, text/plain, */*',
                    'Content-Type': 'application/json',
                }
            });
            res = await res.json();
        } catch (error) {
            console.log('An error occured while deleting.', error);
        }
    }

    return (
        <>
            <Head>
                <title>facebook</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="./facebook.png" />
            </Head>
                    <Header />
                    <Feed />
            <div>
                {
                    mflix.map((post) => {
                        return (
                            <>
                                <div className={style.outer_div} key={post._id}>
                                    <div className={style.user_info_div}>
                                        <Image alt="" src="/1.png" width={45} height={40} style={{borderRadius:"50%"}}/>
                                        <div className={style.user_info}>
                                            <p style={{width:"100px"}}>{session?.user?.name}</p>
                                            <p style={{ fontSize: "14px", width: "140px", color: "rgb(130, 130, 130)", marginTop: '5px' }}>{post.date}</p>
                                        </div>
                                        <div className={style.deletebtn}>
                                            <BsThreeDots style={{cursor:"pointer",marginRight:"2px"}}/>
                                            <RxCross2 onClick={() => handleDelete(post._id)} style={{cursor:"pointer"}}/>
                                        </div>
                                    </div>
                                    <div>
                                        <div className={style.caption_div}>
                                            <p>{post.name}</p>
                                        </div>
                                        <Image src={post.base64} width={600} height={400} alt="Uploaded Image" className={style.image} />

                                        {/* Comment Section Start */}
                                        <CommentPost />
                                        {/* Comment Section End */}

                                    </div>
                                </div>
                            </>
                        )
                    })
                }
                <div>
                </div>
            </div>
        </>
    )
}


export async function getServerSideProps() {

    try {
        const client = await clientPromise;
        const db = client.db("facebook");

        const mflix = await db
            .collection("data")
            .find({})
            .sort({ _id: -1 })
            .limit(10)
            .toArray();


        return {
            props: { mflix: JSON.parse(JSON.stringify(mflix)) },
        };
    } catch (e) {
        console.error(e);
    }
}